# Generated by Django 4.2.11 on 2024-05-02 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='images')),
                ('scientific_name', models.CharField(max_length=100)),
                ('use', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=100)),
                ('cost', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
